---
title: "Ancient Chinese Poems"
author: "DigitCoral"
date: "`r Sys.Date()`"
output: html_document
---

------------------------------------------------------------------------

```{r settings,echo=FALSE,results='hide',fig.keep='all', message=FALSE,warning=FALSE}
Sys.setlocale("LC_ALL","Chinese") #<--set for showing Chinese 
library(googlesheets4)
library(RColorBrewer)
library(wordcloud)
library(dplyr) #<-- for "select" function
```

```{r gshets,echo=FALSE, message=FALSE,warning=FALSE}

gs4_deauth() #<--use only for googlesheets shared as 'anyone with the link'

rw_ac_poems <- read_sheet("https://docs.google.com/spreadsheets/d/1aKXxr4WZh0FOCivLzTFdYkcCHaulDlG9jtPpoDEUvo0/edit?usp=sharing", sheet = "Poems")
#https://docs.google.com/spreadsheets/d/1aKXxr4WZh0FOCivLzTFdYkcCHaulDlG9jtPpoDEUvo0/edit?usp=sharing

#head(rw_ac_poems)
p_count <- nrow(rw_ac_poems)
```

#### ***我收集了约从周朝早期（约1000BC）至近现代新中国（约1949AD)的[`r p_count[1]`]{style="color:red"}首中国古诗词。它们每一首都是文化艺术的瑰宝。在此基础上，我又标出其中的名词、代词、动词、形容词、副词和量词，进行分析，如高频词图等。这些数据也适用于AI学习，或许可以创造新的迷人诗句***

#### ***I have collected [`r p_count[1]`]{style="color:red"} ancient Chinese poems, ranging from early Zhou Dynasty (\~1000BC) to new PRC established (\~1949AD). Each of them is a treasure of culture. Then I marked out the nouns, pronouns, verbs, adjectives, adverbs & quantifiers words, then do the exploration, like the word cloud, etc. The data are also good for AI learning, which may help create new charming poems...***

------------------------------------------------------------------------

#### ***古诗中的名词、代词的高频词***
#### ***The word cloud of the nouns or pronouns used in ancient Chinese poems***

```{r dataClean,echo=FALSE, message=FALSE,warning=FALSE}

acp_cl <- rw_ac_poems
#acp_cl$cl_Time <- sapply(strsplit(na.omit(acp_cl$Time)," "), '[', 1)

# ---------- noun part ----------

cols_n <- max(stringr::str_count(na.omit(acp_cl$Noun_Pro),"/")) + 1

colm_n <- paste("col_n",1:cols_n)

acp_cl <-
  tidyr::separate(
    data = acp_cl,
    col = Noun_Pro,
    sep = "/",
    into = colm_n,
    remove = FALSE
  )

Noun_only <- select(acp_cl,starts_with("col_n"))
Nouns <- data.frame(Noun_Pro=na.omit(unlist(Noun_only))) #<--attach columns of values into one column
Nouns$Noun_Pro <- factor(Nouns$Noun_Pro,levels=as.character(names(sort(table(Nouns$Noun_Pro),decreasing=T)))) 

Noun_freq <- as.data.frame(table(Nouns$Noun_Pro))

wordcloud(words=Noun_freq$Var1,freq=Noun_freq$Freq,min.freq=1,
          max.words=100, random.order=FALSE, rot.per=0.35,
          colors=brewer.pal(8,'Dark2'))
```

### ***古诗中的动词的高频词***
### ***The word cloud of the verbs used in ancient Chinese poems***

```{r verbPart,echo=FALSE, message=FALSE,warning=FALSE}
# ----------- verb part -----------

cols_v <- max(stringr::str_count(na.omit(acp_cl$Verb),"/")) + 1

colm_v <- paste("col_v",1:cols_v)

acp_cl <-
  tidyr::separate(
    data = acp_cl,
    col = Verb,
    sep = "/",
    into = colm_v,
    remove = FALSE
  )
Verb_only <- select(acp_cl,starts_with("col_v"))
Verbs <- data.frame(Verbs=na.omit(unlist(Verb_only))) #<--attach columns of values into one column
Verbs$Verb <- factor(Verbs$Verb,levels=as.character(names(sort(table(Verbs$Verb),decreasing=T))))

Verb_freq <- as.data.frame(table(Verbs$Verb))

wordcloud(words=Verb_freq$Var1,freq=Verb_freq$Freq,min.freq=1,
          max.words=100, random.order=FALSE, rot.per=0.35,
          colors=brewer.pal(8,'Dark2'))
```

### ***古诗中的形容词、副词的高频词***
### ***The word cloud of the adjectives, adverbs used in ancient Chinese poems***

```{r adjPart,echo=FALSE, message=FALSE,warning=FALSE}
# ------------ adjective part ------------

cols_a <- max(stringr::str_count(na.omit(acp_cl$Adj_Adv),"/")) + 1

colm_a <- paste("col_a",1:cols_a)

acp_cl <-
  tidyr::separate(
    data = acp_cl,
    col = Adj_Adv,
    sep = "/",
    into = colm_a,
    remove = FALSE
  )
Adj_only <- select(acp_cl,starts_with("col_a"))
Adjs <- data.frame(Adjs=na.omit(unlist(Adj_only))) #<--attach columns of values into one column
Adjs$Adj <- factor(Adjs$Adj,levels=as.character(names(sort(table(Adjs$Adj),decreasing=T))))

Adj_freq <- as.data.frame(table(Adjs$Adj))

wordcloud(words=Adj_freq$Var1,freq=Adj_freq$Freq,min.freq=1,
          max.words=100, random.order=FALSE, rot.per=0.35,
          colors=brewer.pal(8,'Dark2'))

```

### ***古诗中的量词的高频词***
### ***The word cloud of the quantifiers used in ancient Chinese poems***

```{r quantPart,echo=FALSE, message=FALSE,warning=FALSE}
# ------------ Quantifier part ------------

cols_q <- max(stringr::str_count(na.omit(acp_cl$Quantifier),"/")) + 1

colm_q <- paste("col_q",1:cols_q)

acp_cl <-
  tidyr::separate(
    data = acp_cl,
    col = Quantifier,
    sep = "/",
    into = colm_q,
    remove = FALSE
  )
Quant_only <- select(acp_cl,starts_with("col_q"))
Quants <- data.frame(Quants=na.omit(unlist(Quant_only))) #<--attach columns of values into one column
Quants$Quant <- factor(Quants$Quant,levels=as.character(names(sort(table(Quants$Quant),decreasing=T))))

Quant_freq <- as.data.frame(table(Quants$Quant))

wordcloud(words=Quant_freq$Var1,freq=Quant_freq$Freq,min.freq=1,
          max.words=100, random.order=FALSE, rot.per=0.35,
          colors=brewer.pal(8,'Dark2'))

```
